name: fashion_shop
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/Articles/
    - assets/images/exposure/
    - assets/icons/

  
  fonts:
    - family: DMSans
      fonts:
        - asset: assets/Fonts/DM sans/DMSans-Bold.ttf
        - asset: assets/Fonts/DM sans/DMSans-BoldItalic.ttf
        - asset: assets/Fonts/DM sans/DMSans-Italic.ttf
        - asset: assets/Fonts/DM sans/DMSans-Medium.ttf
        - asset: assets/Fonts/DM sans/DMSans-MediumItalic.ttf
        - asset: assets/Fonts/DM sans/DMSans-Regular.ttf
  
