name: fashion_shop
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/Articles/
    - assets/images/exposure/
    - assets/icons/

  fonts:
    - family: Heebo
      fonts:
        - asset: assets/Fonts/Heebo/Heebo-Black.ttf
        - asset: assets/Fonts/Heebo/Heebo-Bold.ttf
        - asset: assets/Fonts/Heebo/Heebo-ExtraBold.ttf
        - asset: assets/Fonts/Heebo/Heebo-ExtraLight.ttf
        - asset: assets/Fonts/Heebo/Heebo-Light.ttf
        - asset: assets/Fonts/Heebo/Heebo-Medium.ttf
        - asset: assets/Fonts/Heebo/Heebo-Regular.ttf
        - asset: assets/Fonts/Heebo/Heebo-SemiBold.ttf
        - asset: assets/Fonts/Heebo/Heebo-Thin.ttf
